### PR TITLE
Add mongodb 3.6

### PR DESCRIPTION
**Pull request by omron93**
No rpms for mongodb 3.6 ready yet. This PR is mainly to test that other versions works with these changes too.

### CODE REVIEW

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
[test-openshift]

**Comment by jocelynthode** [comment]
Hey, can we expect this PR to be merged soonish ?

**Comment by omron93** [comment]
@jocelynthode rh-mongodb36 SCL is not ready in CentOS yet, so I would rather wait for it.

@khardix Do you have any estimation when builds could be properly tagged for CentOS?

**Comment by khardix** [comment]
@omron93 @jocelynthode I'm currently waiting for [forgotten go-toolset dependency](https://bugs.centos.org/view.php?id=14625). After that, it should be only a few days.

**Comment by khardix** [comment]
@omron93 @jocelynthode Well, it was done faster than I anticipated! The builds should be available in the [sclo7-rh-mongodb36-rh-candidate](https://cbs.centos.org/koji/taginfo?tagID=1474) tag.

**Comment by jocelynthode** [comment]
Nice! Thanks for the work guys

**Comment by omron93** [comment]
Rebased.
[test-openshift]

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
Tests are passing (fedora CI is failing because of issue not caused by this PR, I'll fix it in separate PR) + new version doesn't differ much (only mongodb version changes + changes in bindIP: configuration).

**Pull request merged**
