### PR TITLE
Optimize Dockerfiles (2.6 - 3.2 & RHEL)

### PR DESCRIPTION
**Pull request by rhcarvalho**
Follows up on #193.

### CODE REVIEW

**Comment by bparees** [comment]
please squash or i will squash+merge and you'll be upset there is no merge commit :)

**Comment by praiskup** [comment]
@bparees out of curiousity -- I'm the one who absolutely hates non-linear git logs with merge commits, so I'm curious who likes merge-commits and why :).  Or was that irony ? :)

**Comment by bparees** [comment]
@praiskup i think the issue is preserving the original commits that @rhcarvalho created so he can easily clean up branches that have been merged via scripting.

**Comment by rhcarvalho** [comment]
I'm okay with whatever @bparees decides.

**Comment by bparees** [comment]
I prefer the merge commit for the same reason as @rhcarvalho (branch deletion workflow)

**Comment by rhcarvalho** [comment]
@bparees do you know the difference between the "default" and "ci.centos.rg" checks?

My brain cannot parse https://ci.openshift.redhat.com/jenkins/job/mongodb/382/console at the moment...

**Comment by bparees** [comment]
not immediately obvious to me what is failing either.

**Comment by praiskup** [comment]
> I prefer the merge commit for the same reason as @rhcarvalho (branch deletion workflow)

We talk about branch deletion within @rhcarvalho 's namespace in this case?  I'm reading again and again :) and I don't understand what the "merge commit" actually helps with.

I've noticed it is now (finally!!) possible to do 'rebase and merge' button for PRs in github, so there is no need to go into terminal anymore if you just want to push the commits, keeping the original author, without breaking linearity and readability in git-log by ugly merge commits  (this doesn't solve the situation here: IFF the set of commits needs to be squashed from logical POV).

**Comment by bparees** [comment]
> We talk about branch deletion within @rhcarvalho 's namespace in this case? 

yes

**Comment by praiskup** [comment]
> yes

So we expecte PR submitter is going to keep the temporary branch forever, having the same hashes in commits? (just to be sure I understand correctly).

**Comment by bparees** [comment]
> So we expecte PR submitter is going to keep the temporary branch forever, having the same hashes in commits? (just to be sure I understand correctly).

no, we expect the PR submitter is going to run a script that checks his local branches against upstream to see if the local branch commits are merged upstream and if so, delete the local branch.

which only works if the commits aren't rewritten when they get merged upstream.

at least I think that is what @rhcarvalho was getting at.  I run a script like that and while i haven't investigated it, i assume it would fail if we didn't use merge commits.

**Comment by praiskup** [comment]
Interesting, thanks for clarification.  I personally dislike this workflow, because temporary branches are just temporary branches -- yes, with a bit of comfort during PR, but `git log | grep Merge:  | wc -l` is then **forever** in git log, and that's what will survive all of us (even days when nobody will remember what github.com was about).

**Comment by praiskup** [comment]
Sorry for off topic discussion above ^^, but thanks again for clarification.

**Comment by rhcarvalho** [comment]
Taking on the off-topic for a last round, just because @praiskup taught me something about `git apply` flags...

@praiskup have you tried `git log --no-merges`?

Works for me in this repo.

**Comment by rhcarvalho** [comment]
@bparees squashed, let's see what Jenkins will say now...

**Comment by praiskup** [comment]
@rhcarvalho I believe I already tried this some time ago, thanks reminding me this but truth is that I don't want to hide something which is already there.

I can help myself, the patches we merge in github are basically fast-forward merges, so there's little benefit of having merge commits in place, it is just there to make it a bit less tidy from "historical" point of view ... (especially now, when github has appropriate feature, so we can't blame our laziness :)).

**Comment by rhcarvalho** [comment]
@bparees looks like `yum` is failing? Could it be some env problem?
https://ci.openshift.redhat.com/jenkins/job/mongodb/383/console

**Comment by bparees** [comment]
@rhcarvalho yum's been having problems all day in all our CI stuff, i think it may be the mirrors that we use from the ec2 instances?  anyway i'm hoping it resolves itself soon and i'll revisit this then.  feel free to keep hammering the [test] tag yourself though.

**Comment by rhcarvalho** [comment]
- :x: **RHEL7** build was aborted by anonymous -- [console](https://coreservices-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhscl-images-mongodb-rh/18/console)
- :x: **ci.centos.org** failed with a DockerHub error "Tag centos7 not found in repository docker.io/library/centos" -- [console](https://ci.centos.org/job/SCLo-container-mongodb-rh/9/console)
- :white_check_mark: **default** is green -- [console](https://ci.openshift.redhat.com/jenkins/job/mongodb/384/)

@hhorak how to re-trigger the RHEL7 and CentOS builds? Could we add that information to the README or CONTRIBUTING?

@hhorak @bparees maybe we should rename **"default"** to something more meaningful? WDYT?

**Comment by rhcarvalho** [comment]
Got a green from the RHEL7 job that ran early this morning (no idea what caused it to be re-run):
- :white_check_mark: **RHEL7** is green -- [console](https://coreservices-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhscl-images-mongodb-rh/19/console)

**Comment by omron93** [comment]
> @hhorak how to re-trigger the RHEL7 and CentOS builds? Could we add that information to the README or CONTRIBUTING?

Members of sclorg organization can use [test] in PR comment.

> maybe we should rename "default" to something more meaningful? WDYT?

+1

> Got a green from the RHEL7 job that ran early this morning (no idea what caused it to be re-run):

I've rerun it. There was a problem with full disk in Jenkins slave.

**Comment by rhcarvalho** [comment]
thanks @omron93! So now we've got 3 greens:

https://coreservices-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhscl-images-mongodb-rh/20/
https://ci.centos.org/job/SCLo-container-mongodb-rh/10/
https://ci.openshift.redhat.com/jenkins/job/mongodb/384/

@bparees PTAL

**Pull request merged**
