### PR TITLE
Add support for REGISTRY parameter

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@mfojtik what is this for?

**Comment by mnagy** [comment]
+1 for this. @mfojtik will you add this to other images as well?

**Comment by mfojtik** [comment]
@rhcarvalho honestly, I don't remember now but it has something to do with the push images job. @mnagy what you want to use this for? ;-)

**Comment by mnagy** [comment]
Ah, never mind. I wanted to use it for custom images under my own docker namespace, but I just realized that's actually a part of IMAGE_NAME :)

**Pull request closed without merging**
