### PR TITLE
[stalled] Change RH required labels based on updated spec

### PR DESCRIPTION
**Pull request by hhorak**
For full spec, see https://github.com/projectatomic/ContainerApplicationGenericLabels/blob/master/vendor/redhat/labels.md

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@hhorak sorry for the long delay.
Could you please confirm this is still up to date?

LGTM @bparees @mfojtik PTAL

**Comment by bparees** [comment]
Lgtm pending confirmation.

**Comment by hhorak** [comment]
Actually internal build system does not support the new variant of labels, so we need to wait with the changing. I have no better info when we'll be ready to implement this.

**Comment by mfojtik** [comment]
@hhorak did they changed? :-)

**Comment by rhcarvalho** [comment]
@mfojtik see https://github.com/openshift/sti-python/pull/79
We can close this for tidiness and open a new PR if labels need to change in the future.

**Comment by hhorak** [comment]
Closing, since osbs does not allow these new specs yet.

**Pull request closed without merging**
