### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by jhadvig**
- Renamed `mongo-replica.json` to `mongodb-replica.json` for consistency 
- Updated mongodb replica README
- Got rid of teardown.sh

### CODE REVIEW

**Comment by jhadvig** [comment]
@mfojtik PTAL

**Comment by mfojtik** [comment]
@jhadvig can you please add `oc delete all ...` to README  instead of teardown?

**Comment by mfojtik** [comment]
LGTM otherwise

**Comment by jhadvig** [comment]
@mfojtik updated

**Pull request merged**
