### PR TITLE
Added container-quickstarts as an 'examples' submodule. This contains…

### PR DESCRIPTION
**Pull request by jbornemann**
This contains the updated mongodb statefulset quickstart example from the red hat COP repository. It looks like it might have been copied from there originally.

### CODE REVIEW

**Comment by omron93** [comment]
This PR looks good to me. Linked container-quickstart contains new information IMPOV.

@jbornemann Is it possible to get commit right into this repository?
Also removed README contained some info about scaling replicaset. Mainly about scaling down and absence of removing members from mongodb configuration. So after big scale down replicaset could be unreachable.

**Comment by jbornemann** [comment]
> Is it possible to get commit right into this repository?

Sorry, not sure what you mean. Do you mean embed the example directly in this repository? Part of the reasoning behind having it be a submodule was to reduce duplication of work. The RH Container COP actively maintains those examples. Let me know if I misunderstand. 

> Also removed README contained some info about scaling replicaset. Mainly about scaling down and absence of removing members from mongodb configuration. So after big scale down replicaset could be unreachable.

We could certainly add part/all of the document back.

**Comment by omron93** [comment]
> Sorry, not sure what you mean. Do you mean embed the example directly in this repository? Part of the reasoning behind having it be a submodule was to reduce duplication of work. The RH Container COP actively maintains those examples. Let me know if I misunderstand.

I understand. I thought about whats a process of contributing into that repo. And if it would be possible to be added as collaborator to that repo to be able to participate in maintaing of this example...

> We could certainly add part/all of the document back.

Thanks.

**Comment by jbornemann** [comment]
> I understand. I thought about whats a process of contributing into that repo. And if it would be possible to be added as collaborator to that repo to be able to participate in maintaing of this example...

You could ask. I believe Eric Sauer, and Andrew Block are the owners of that repository. You will probably have to create a fork, and submit PRs from your fork.

**Comment by hhorak** [comment]
Thanks @jbornemann, that is very interesting. I'm thinking whether including such a repo as a submodule is the best way here, since the repository includes much more than just mongodb examples. Wouldn't a link from README.md to the remote directory be better? If we want to use the remote templates for testing, we can always download latest template and run it, it doesn't need to be a submodule..

**Comment by jbornemann** [comment]
Sure, that's fine by me. I've updated

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by hhorak** [comment]
mongodb container is not maintained any more in this org. closing.

**Pull request closed without merging**
