### PR TITLE
update maintainer and remove dead code

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@mfojtik ptal pending maintainer

**Comment by bparees** [comment]
argh. merged the wrong tab.  will revert if necessary.

**Comment by jhadvig** [comment]
@bparees the cleanup looks good, but not sure if the `MAINTAINER` addresses are correct. The address for centos image should be `SoftwareCollections.org <sclorg@redhat.com>` and for rhel there should be none (at least thats what I see in the ruby-2.2). And whats with the `dev@lists.openshift.redhat.com` @smarterclayton suggested ?

**Comment by hhorak** [comment]
Please, don't use dev@lists.openshift.redhat.com, the images are supposed to be not only for OpenShift.

**Comment by bparees** [comment]
fixing here: 
https://github.com/openshift/mongodb/pull/65

**Pull request merged**
