### PR TITLE
Split main scripts for standalone server and replication.

### PR DESCRIPTION
**Pull request by omron93**
The aim of this PR is to split run-mongod into main replication and standalone script.

I would like to:
1) Make code more clean and readable
- current situation:
  - run-mongod initiate -> execed into initiate_replica.sh -> it run run-mongod in background -> this background run-mongod after some coding execked mongod
  - run-mongod (replicated) -> run in background replica_supervisor.sh
  - run-mongod -> run mongod in background -> create users -> exec mongod
  
  Main code is in one script and decision is made environmental variables. Also I don't like that if I want to see a flow of the script that I have to look at 3+ files to find it.
  - in this PR:
    - run-mongod -> run mongod in background -> create users -> exec mongod
  - run-mongod-replication -> run replset_supervisor.sh in background (according to first parameter (initiate) - initiates replicaset or tries to add current node to replset ) and exec mongod

2) Separating these scripts allows us to easily add other scenarios - for example add sharding support -> new script run-mongod-sharding ...

3) Make mongodb more similar to other databases (mysql and postgresql both have separated scripts for standalone and master/slave replication)

**I didn't add new code** (only restructured old one)
- run-mongod and run-mongod-replication are only splited (removed if statement) original run-mongod
- replset_supervisor.sh is joined replica_supervisor.sh and initiate_replica.sh and added if according to first argument of run-mongod-replication
- from common.sh removed unneeded function run_mongod_supervisor

@hhorak @bparees @rhcarvalho @php-coder Please take a look.

### CODE REVIEW

**Comment by hhorak** [comment]
[test]

**Comment by rhcarvalho** [comment]
I don't have the bandwidth to manually test this thoroughly, and I know @php-coder is on PTO this week.

That said, having briefly glanced the changes and trusting the description I don't see a problem with proceeding with it.
Only one thing caught my attention: @omron93 the patch is +740 -582, thus adding a net of 158 lines. What are those?

@bparees can we engage somebody from AOS QE to help us with functional testing here? We have very competent people like @wanghaoran1988.

**Comment by bparees** [comment]
@rhcarvalho it definitely shouldn't fall to you.  The SCL team is engaged w/ our QE team and can definitely ask them to sniff test this before we merge it, or can have their own QE team test it.

Either way I agree it merits some outside QE oversight.

**Comment by omron93** [comment]
> Only one thing caught my attention: @omron93 the patch is +740 -582, thus adding a net of 158 lines. What are those?

run-mongod and run-mongod-replication shares their first 45 lines. So while adding run-mongod-replication copy of these lines were added (was not removed from run-mongod -> + line in patch) and this was done for all 4 versions of mongod.

**Comment by wanghaoran1988** [comment]
I finished the testing today, no issues found, thanks

**Pull request merged**
