### PR TITLE
add readinessProbe

### PR DESCRIPTION
**Pull request by wanghaoran1988**
Add a readinessProbe for this template

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@wanghaoran1988 thank you and sorry for the long delay! LGTM.

@bparees could you please merge this?

**Comment by mfojtik** [comment]
hold on merging this. we dunno if this does not create chicken egg problem
with members discovery.

**Comment by rhcarvalho** [comment]
@mfojtik I've tested this, it works.

**Comment by mfojtik** [comment]
i will add liveness check as a followup

**Pull request merged**
