### PR TITLE
rename username variable to user

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
rename to match other DB images.  @jhadvig ptal.

**Comment by bparees** [comment]
@jhadvig make test is failing for me locally as well as in jenkins, fails for master too.  
- echo '  Testing user privileges'
  Testing user privileges
- mongo_cmd 'db.testData.insert({ y : 1 });'
- docker run --rm openshift/mongodb-24-centos7-candidate mongo test_db --host 172.17.0.165 -u user -p pass --eval 'db.testData.insert({ y : 1 });'
  MongoDB shell version: 2.4.9
  connecting to: 172.17.0.165:27017/test_db
  Tue Apr 21 04:09:14.246 SyntaxError: Unexpected end of input

**Comment by mfojtik** [comment]
@bparees that is my fault, I broke tests when I was doing replicas and I still didn't had a time to fix them :-(

Btw. the error above can be fixed by compressing the string (removing the white spaces).... Don't ask...

**Comment by bparees** [comment]
@mfojtik ok i'm going to check in that fix w/ this PR for now...

**Comment by mfojtik** [comment]
@bparees OK, I'm slowly getting there ;-) I still dunno what I screwed up in the entrypoint so the spaces are now problem....

**Comment by jhadvig** [comment]
@bparees I've already send a PR fixing the envar last week, but was waiting for @mfojtik to fix the tests :P 
https://github.com/openshift/mongodb/pull/19/files

**Comment by bparees** [comment]
@jhadvig ah, sorry.  glad you agree w/ the change anyway :)

i'm going to merge this one, i need to get this in for the beta release.

**Comment by jhadvig** [comment]
@bparees :+1: 
just wanted to sync regarding closing the other one.

**Pull request merged**
