### PR TITLE
Updated README.md docker run command after requiring database env var

### PR DESCRIPTION
**Pull request by soltysh**
@jhadvig PTAL, you've missed that in https://github.com/openshift/mongodb/pull/5

### CODE REVIEW

**Comment by mfojtik** [comment]
Lgtm

**Comment by soltysh** [comment]
Please re[test] I don't understand the failure.

**Comment by mfojtik** [comment]
set +x would help to clear the Jenkins output

**Comment by soltysh** [comment]
Maybe, but you still want to see what command start/ends where somehow. Since the build succeeded and I got LGTM -> merging.

**Comment by jhadvig** [comment]
@soltysh thx :+1:  :)

**Pull request merged**
