### PR TITLE
remove test for gid value

### LINKED ISSUE #109: GID 998 will be unusable in rhel7.2
Per https://github.com/openshift/mongodb/blob/master/2.4/Dockerfile.rhel7#L28-L32 mongodb user must always be uid=184 and gid=998   however in rhel7.2 images gid 998 is already in use by systemd packages.

```
docker run ${INTERNAL_REGISTRY}/rhel7.2 cat /etc/group | grep 998
systemd-bus-proxy:x:998:
```

When installing on rhel7.2 mongodb is uid=184 gid=995
So what to do? 

@jhadvig as you wrote the comment referenced above

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/mongodb/issues/109

### CODE REVIEW

**Comment by bparees** [comment]
@mnagy @rhcarvalho ptal.

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@sdodson fyi.

**Comment by rhcarvalho** [comment]
@bparees RHEL build failed.
Could we do the changes to the chmod in a separate PR or at least a separate commit?
That change has a different reason to be, and IMHO would be better off on its own (e.g. in case we need to revert it, or for clarity when somebody is reading the commit message and trying to understand why those lines changed).
Other than that LGTM.

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
@rhcarvalho I don't see any reason for that chmod to be its own RUN layer and i don't see a need for a separate commit or PR for a trivial change like that.

the failure was because of a cut+paste issue in the 2.6 images, fixed.

**Comment by mnagy** [comment]
LGTM

**Pull request merged**
