### PR TITLE
install syspath packages in rhel7/centos7

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by phracek** [comment]
Tests are failing on fedora base image `f26/s2i-base`. This image does not exist.

**Comment by pkubatrh** [comment]
mongodb is not part of Fedora anymore in the recent releases so removing completely

Note that rhel8 CI is likely to fail due to missing networking features in podman

**Comment by pkubatrh** [comment]
Oh right, no rhel8 version, makes sense. Lets try openshift as well

[test-openshift]

**Comment by phracek** [comment]
It looks like rhel7-openshift is working.

**Review by phracek — APPROVED** [review]
LGTM. Thanks for fixing!

**Pull request merged**
