### PR TITLE
Specify HOME variable

### PR DESCRIPTION
**Pull request by omron93**
Add correct HOME variable.

It fixes bugs like this -  https://bugzilla.redhat.com/show_bug.cgi?id=1265976

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM [test]

**Comment by jhadvig** [comment]
@omron93 wants there a bug in mongo24 where the HOME for the mongo user was wrong ?

**Comment by jhadvig** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1206151

**Comment by omron93** [comment]
@jhadvig What is wrong about HOME=/var/lib/mongodb?
Even in the mentioned bug you wants this change. And this mainly solves that when you run with "random" UID (docker run -u ...) the HOME is set to / and user can't write there.

**Comment by jhadvig** [comment]
@omron93 nothings wrong, the change itself is good :+1: 
Just wanted to point out the reason, so when we look back, we know why the change was done(partially)

**Pull request merged**
