### PR TITLE
Revert "Add MONGODB_TEXT_SEARCH_ENABLED flag"

### PR DESCRIPTION
**Pull request by bparees**
Reverts openshift/mongodb#144

@mfojtik this appears to be hanging the 2.4 tests in the push job (and confirmed by me locally) and it doesn't look like the PR had tests run on it?

### CODE REVIEW

**Comment by mfojtik** [comment]
@bparees for some reason I thought the tests are run automatically when somebody from the committer group open a PR... sorry for this, going to fix this ASAP.

**Comment by mfojtik** [comment]
@bparees interesting:

``` console
=>  Waiting for MongoDB daemon up
error command line: unrecognised option 'textSearchEnabled'
use --help for help
```

https://docs.mongodb.org/v2.4/tutorial/enable-text-search/

i'm confused now :-)

**Comment by rhcarvalho** [comment]
@mfojtik looks like you missed the "setParameter" part: https://docs.mongodb.org/v2.4/reference/configuration-options/#setParameter

The line in the config file should be:

```
setParameter = textSearchEnabled=<value>
```

**Comment by mfojtik** [comment]
@rhcarvalho yes, already fixed in the other PR...

**Pull request merged**
