### PR TITLE
Use shared functions from common submodule also in replication tests

### PR DESCRIPTION
**Pull request by omron93**
Replication tests are currently broken. I hope this will fix them.

### CODE REVIEW

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
Since the tests have a `print_logs` function it would be a good idea to call it before returning a failure.

The function is also something that would be nice to have in common scripts as I expect all of the repositories would benefit from it.

**Comment by omron93** [comment]
> Since the tests have a print_logs function it would be a good idea to call it before returning a failure.

@pkubatrh What is the "most elegant" way how to do it?
There was set `trap print_logs ERR` but `set -e` ends it before logs are printed. On the other hand it's useless and annoying to print logs if all tests pass.

**Comment by pkubatrh** [comment]
Calling it explicitly right before `return 1` would work.

Best thing would be to actually call it even when all tests pass - the project should get deleted on a pass, so nothing is going to get printed out.

**Comment by pkubatrh** [comment]
>the project should get deleted on a pass, so nothing is going to get printed out.

Although it seems that the project instance is still available for a few moments after it gets flagged for removal... So maybe also add a smal sleep at the end of the test suite to sync up.

**Comment by omron93** [comment]
[test-openshift]

Now includes changes from https://github.com/sclorg/container-common-scripts/pull/51 . Will remove definition o functions after the PR is merged.

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
[test-openshift]

(local functions are removed)

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
Tests are finally passing. So merging.

**Pull request merged**
