### PR TITLE
add imagestream and examples for mongo on ppc64le

### PR DESCRIPTION
**Pull request by jeffdyoung**
add imagestream and examples for mongo 3.6 on ppc64le

### CODE REVIEW

**Comment by omron93** [comment]
@jeffdyoung Is this final form to be merged? Or something in planning changed it needs to be adjusted?

Also please rebase to reflect latest changes (`registry.access.redhat.com` to `registry.redhat.io` change) migration.

**Comment by jeffdyoung** [comment]
@omron93 I need to find time to finish this up. Things have changed since this commit. I will do my best to finish this week. Thanks!

**Comment by omron93** [comment]
>  I will do my best to finish this week.

@jeffdyoung No problem, no hurry. I only wanted to know what is the status.

**Comment by jeffdyoung** [comment]
@omron93 Its ready. Thanks!

**Comment by hhorak** [comment]
LGTM, thanks!

**Pull request merged**
