### PR TITLE
Update docs with resize command

### PR DESCRIPTION
**Pull request by 0xmichalis**

### CODE REVIEW

**Comment by 0xmichalis** [comment]
@mnagy ping

**Comment by 0xmichalis** [comment]
@mfojtik fyi

**Comment by mfojtik** [comment]
@kargakis LGTM, thanks a lot for doing this!

**Comment by mfojtik** [comment]
@kargakis merge at your will :)

**Comment by 0xmichalis** [comment]
@mfojtik I don't have write access to the repo

**Pull request merged**
