### PR TITLE
Fix templates according to `openshift/origin`

### PR DESCRIPTION
**Pull request by pvalena**
[Replace 'template.openshift.io' with 'openshift.io'](https://github.com/openshift/origin/pull/17922#pullrequestreview-86819501)
 
and 

[Remove ' (Persistent)'](https://github.com/openshift/origin/pull/17922#pullrequestreview-86940496)

### CODE REVIEW

**Comment by pvalena** [comment]
@centos-ci why 3x?

**Comment by pvalena** [comment]
```
14:44:47 Error downloading packages:
14:44:47   rh-mongodb26-gperftools-libs-2.2.1-4.el7.x86_64: [Errno 256] No more mirrors to try.
14:44:47   rh-mongodb26-mongodb-2.6.9-1.el7.x86_64: [Errno 256] No more mirrors to try.
```

**Comment by pkubatrh** [comment]
[test]
[test-openshift]

**Comment by pkubatrh** [comment]
@omron93 can you check and see what went wrong with the openshift tests?

**Comment by pvalena** [comment]
Any news on this?

**Comment by omron93** [comment]
@pvalena I think the reason why tests fails is that they are outdated. So please take a look in #275 which makes them to use shared test functions.

**Comment by pvalena** [comment]
Removed common commit update.

**Comment by pvalena** [comment]
@omron93, do the changes of annotation in template matter to test? It will be soon merged in https://github.com/openshift/origin/pull/17922 anyway :). And I think it should be merged here first.

**Comment by pvalena** [comment]
The build was killed, maybe timeout?

```
13:35:01  ---> Running in 373723d5b939
13:35:03 Loaded plugins: ovl, product-id, search-disabled-repos, subscription-manager
15:14:13 Killed by signal 15.
15:14:13 Build step 'Execute shell' marked build as failure
```

**Comment by omron93** [comment]
> The build was killed, maybe timeout?

Yes, there is 2h timeout.

> @omron93, do the changes of annotation in template matter to test? It will be soon merged in openshift/origin#17922 anyway :). And I think it should be merged here first.

You are right. I"ll merge it.

**Comment by pvalena** [comment]
Thanks!

**Pull request merged**
