### PR TITLE
Initialize replset without deploy hook.

### PR DESCRIPTION
**Pull request by omron93**
This PR is only to show possibility of creating replset without post deploy hook. It is only fast draft, only to get feedback from others.

@php-coder @bparees @rhcarvalho Please take a look and test. I am not sure that it will work (on my local openshift it works), that there is no problem... so I mainly want to get a feedback.

### CODE REVIEW

**Comment by bparees** [comment]
what happens if a new pod comes up with a lower ip address and tries to initialize as the master?

what if the pod w/ the lowest ip wasn't registered as an endpoint yet?

**Comment by omron93** [comment]
@bparees That is only one thing I am not sure about and I can't find anywhere how kubernetes do IP assigning and when it lists pod in service.

Making MONGODB_INITIAL_REPLICA_COUNT mandatory for this type of initializing should solve this.

**Comment by rhcarvalho** [comment]
I'd ask the same questions as @bparees. I think this type of initialization has too many race conditions to work in practice.

The guarantees we have with petsets, and semantics of how things work is different.

Without petsets I'd go for multiple services and multiple DCs, but that's really not what @php-coder was working on, the intent for him was to get the petset example working because of persistent storage...

Even though I would too, like @omron93,  prefer to have code in a single place (copy-paste-per-version, I don't like you!), IMHO the conceptual differences are enough to justify a separate path of implementation.

**Comment by omron93** [comment]
> I'd ask the same questions as @bparees. I think this type of initialization has too many race conditions to work in practice.
> Without petsets I'd go for multiple services and multiple DCs, but that's really not what @php-coder was working on, the intent for him was to get the petset example working because of persistent storage.

@rhcarvalho Would having mandatory `MONGODB_INITIAL_REPLICA_COUNT` fit into "documented limitations" mentined in https://github.com/sclorg/mongodb-container/pull/184#issuecomment-249013321? Do you see any problem with using this variable to determine who should initialize? 

> copy-paste-per-version, I don't like you!

I would also to prefer some solution to this. But I don't have any idea how to solve this and there is no result from discussion about this. However IMPOV with some tooling it is not so hard to deal with this.

> IMHO the conceptual differences are enough to justify a separate path of implementation.

Yes, of course.

**Comment by rhcarvalho** [comment]
> @rhcarvalho Would having mandatory MONGODB_INITIAL_REPLICA_COUNT fit into "documented limitations" mentined in #184 (comment)? Do you see any problem with using this variable to determine who should initialize?

I don't see how that solves the problem @bparees raised.

If users would keep MONGODB_INITIAL_REPLICA_COUNT in sync with the number of replicas (so maybe the name should be REPLICA_COUNT, remove "INITIAL" ...), each pod would need to wait until it can see N other pods to determine who is to perform the initialization.
This "waiting" part has several rough edges to solve:
- what if `dig` returns more IPs than MONGODB_INITIAL_REPLICA_COUNT?
- what if `dig` takes an arbitrary long time (infinity?) to return as many IPs as MONGODB_INITIAL_REPLICA_COUNT?
- what if `dig` returns MONGODB_INITIAL_REPLICA_COUNT IPs, pod A thinks it's got the lowest IP, but then pod B gets restarted and gets an even lower IP... does it run initialization again?

We really get into solving a consensus problem if we are to guarantee that all N pods see the same list of IPs when they decide who does initialization.

With petsets and hostnames a pod is independent of all other pods to decide if it should perform initialization.

**Comment by omron93** [comment]
@rhcarvalho I see. Sorry I was somehow missing fact that newly added pods run the same code with same environment. I am ashamed :-)

Now I see that is probably not possible.

Thanks. Closing since this PR is wrong.

**Comment by rhcarvalho** [comment]
> I am ashamed :-)

Don't be! It takes some good discussions and cross-validation to get this moving forward. Thank you!

**Pull request closed without merging**
