### PR TITLE
Add support for SSL/TLS connections with s2i extending

### PR DESCRIPTION
**Pull request by omron93**
Add support for SSL/TLS connections with s2i extending

+ use mongo shell with scripts instead of --eval parameter (--eval
caused problems with ssl parameters)

Inspired by #266 . @jkupferer or @jbornemann Is this change acceptable for you use case?

@mmuzila Could you please review this?

### CODE REVIEW

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
Rebased.

[test-openshift]

**Comment by omron93** [comment]
[test-openshift][test]

**Comment by omron93** [comment]
[test-openshift]

**Comment by omron93** [comment]
@UncleAlbie Finally ready for review and merge. So when you have to look into container, you can take this PR.

**Review by panovotn — APPROVED** [review]
Seems ok to me. Good work!

**Comment by omron93** [comment]
@UncleAlbie Thanks

[test][test-openshift]

**Pull request merged**
